apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-app
  template:
    metadata:
      labels:
        app: blazor-app
    spec:
      containers:
      - name: blazor-app
        image: appimage.azurecr.io/cloudsmartops/demoblazorserverappwithdockercompose:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blazor-app
spec:
  type: LoadBalancer
  selector:
    app: blazor-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: database-data
      containers:
      - name: database
        image: mcr.microsoft.com/database/server:2019-latest
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: database-data
          mountPath: /var/opt/database/data
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "mypassword"
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
