apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blazor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-blazor-app
  template:
    metadata:
      labels:
        app: my-blazor-app
    spec:
      containers:
        - name: my-app
          image: appimage.azurecr.io/cloudsmartops/demoblazorserverappwithdockercompose:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-blazor-app
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

